<!DOCTYPE html>



  


<html class="theme-next muse use-motion" lang="zh-Hans">
<head><meta name="generator" content="Hexo 3.8.0">
  <meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta name="theme-color" content="#222">









<meta http-equiv="Cache-Control" content="no-transform">
<meta http-equiv="Cache-Control" content="no-siteapp">
















  
  
  <link href="/lib/fancybox/source/jquery.fancybox.css?v=2.1.5" rel="stylesheet" type="text/css">







<link href="/lib/font-awesome/css/font-awesome.min.css?v=4.6.2" rel="stylesheet" type="text/css">

<link href="/css/main.css?v=5.1.4" rel="stylesheet" type="text/css">


  <link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon-next.png?v=5.1.4">


  <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32-next.png?v=5.1.4">


  <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16-next.png?v=5.1.4">


  <link rel="mask-icon" href="/images/logo.svg?v=5.1.4" color="#222">





  <meta name="keywords" content="Hexo, NexT">










<meta name="description" content="最近做了一点尝试，希望用Python生成dxf或者dwg格式文件，以便在Autocad软件中使用。Autocad 一直是二维绘图软件的霸主，这么些年无人能撼动他的地位，而Autodesk公司一直较为封闭，导致很少有开源的第三方库能很好的支持。   DWG: 脱离AutoCAD软件环境读取、写入DWG格式图纸文件,基本无法实现。通过COM自动化操作是一个可选的方案。 DXF: 它被AutoCAD作为">
<meta property="og:type" content="article">
<meta property="og:title" content="使用Python读写DXF和DWG文件">
<meta property="og:url" content="https://njhpq.github.io/2018/12/27/python-autocad/index.html">
<meta property="og:site_name" content="不一">
<meta property="og:description" content="最近做了一点尝试，希望用Python生成dxf或者dwg格式文件，以便在Autocad软件中使用。Autocad 一直是二维绘图软件的霸主，这么些年无人能撼动他的地位，而Autodesk公司一直较为封闭，导致很少有开源的第三方库能很好的支持。   DWG: 脱离AutoCAD软件环境读取、写入DWG格式图纸文件,基本无法实现。通过COM自动化操作是一个可选的方案。 DXF: 它被AutoCAD作为">
<meta property="og:locale" content="zh-Hans">
<meta property="og:updated_time" content="2018-12-27T09:00:32.912Z">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="使用Python读写DXF和DWG文件">
<meta name="twitter:description" content="最近做了一点尝试，希望用Python生成dxf或者dwg格式文件，以便在Autocad软件中使用。Autocad 一直是二维绘图软件的霸主，这么些年无人能撼动他的地位，而Autodesk公司一直较为封闭，导致很少有开源的第三方库能很好的支持。   DWG: 脱离AutoCAD软件环境读取、写入DWG格式图纸文件,基本无法实现。通过COM自动化操作是一个可选的方案。 DXF: 它被AutoCAD作为">



<script type="text/javascript" id="hexo.configurations">
  var NexT = window.NexT || {};
  var CONFIG = {
    root: '/',
    scheme: 'Muse',
    version: '5.1.4',
    sidebar: {"position":"left","display":"post","offset":12,"b2t":false,"scrollpercent":false,"onmobile":false},
    fancybox: true,
    tabs: true,
    motion: {"enable":true,"async":false,"transition":{"post_block":"fadeIn","post_header":"slideDownIn","post_body":"slideDownIn","coll_header":"slideLeftIn","sidebar":"slideUpIn"}},
    duoshuo: {
      userId: '0',
      author: '博主'
    },
    algolia: {
      applicationID: '',
      apiKey: '',
      indexName: '',
      hits: {"per_page":10},
      labels: {"input_placeholder":"Search for Posts","hits_empty":"We didn't find any results for the search: ${query}","hits_stats":"${hits} results found in ${time} ms"}
    }
  };
</script>



  <link rel="canonical" href="https://njhpq.github.io/2018/12/27/python-autocad/">





  <title>使用Python读写DXF和DWG文件 | 不一</title>
  








</head>

<body itemscope="" itemtype="http://schema.org/WebPage" lang="zh-Hans">

  
  
    
  

  <div class="container sidebar-position-left page-post-detail">
    <div class="headband"></div>

    <header id="header" class="header" itemscope="" itemtype="http://schema.org/WPHeader">
      <div class="header-inner"><div class="site-brand-wrapper">
  <div class="site-meta ">
    

    <div class="custom-logo-site-title">
      <a href="/" class="brand" rel="start">
        <span class="logo-line-before"><i></i></span>
        <span class="site-title">不一</span>
        <span class="logo-line-after"><i></i></span>
      </a>
    </div>
      
        <p class="site-subtitle"></p>
      
  </div>

  <div class="site-nav-toggle">
    <button>
      <span class="btn-bar"></span>
      <span class="btn-bar"></span>
      <span class="btn-bar"></span>
    </button>
  </div>
</div>

<nav class="site-nav">
  

  
    <ul id="menu" class="menu">
      
        
        <li class="menu-item menu-item-home">
          <a href="/" rel="section">
            
              <i class="menu-item-icon fa fa-fw fa-home"></i> <br>
            
            首页
          </a>
        </li>
      
        
        <li class="menu-item menu-item-about">
          <a href="/about/" rel="section">
            
              <i class="menu-item-icon fa fa-fw fa-user"></i> <br>
            
            关于
          </a>
        </li>
      
        
        <li class="menu-item menu-item-tags">
          <a href="/tags/" rel="section">
            
              <i class="menu-item-icon fa fa-fw fa-tags"></i> <br>
            
            标签
          </a>
        </li>
      
        
        <li class="menu-item menu-item-archives">
          <a href="/archives/" rel="section">
            
              <i class="menu-item-icon fa fa-fw fa-archive"></i> <br>
            
            归档
          </a>
        </li>
      

      
    </ul>
  

  
</nav>



 </div>
    </header>

    <main id="main" class="main">
      <div class="main-inner">
        <div class="content-wrap">
          <div id="content" class="content">
            

  <div id="posts" class="posts-expand">
    

  

  
  
  

  <article class="post post-type-normal" itemscope="" itemtype="http://schema.org/Article">
  
  
  
  <div class="post-block">
    <link itemprop="mainEntityOfPage" href="https://njhpq.github.io/2018/12/27/python-autocad/">

    <span hidden itemprop="author" itemscope="" itemtype="http://schema.org/Person">
      <meta itemprop="name" content="njhpq@hotmail.com">
      <meta itemprop="description" content="">
      <meta itemprop="image" content="/images/avatar.gif">
    </span>

    <span hidden itemprop="publisher" itemscope="" itemtype="http://schema.org/Organization">
      <meta itemprop="name" content="不一">
    </span>

    
      <header class="post-header">

        
        
          <h1 class="post-title" itemprop="name headline">使用Python读写DXF和DWG文件</h1>
        

        <div class="post-meta">
          <span class="post-time">
            
              <span class="post-meta-item-icon">
                <i class="fa fa-calendar-o"></i>
              </span>
              
                <span class="post-meta-item-text">发表于</span>
              
              <time title="创建于" itemprop="dateCreated datePublished" datetime="2018-12-27T08:42:29+08:00">
                2018-12-27
              </time>
            

            

            
          </span>

          

          
            
          

          
          

          

          

          

        </div>
      </header>
    

    
    
    
    <div class="post-body" itemprop="articleBody">

      
      

      
        <p>最近做了一点尝试，希望用Python生成dxf或者dwg格式文件，以便在Autocad软件中使用。Autocad 一直是二维绘图软件的霸主，这么些年无人能撼动他的地位，而Autodesk公司一直较为封闭，导致很少有开源的第三方库能很好的支持。</p>
<blockquote>
<ul>
<li>DWG: 脱离AutoCAD软件环境读取、写入DWG格式图纸文件,基本无法实现。通过COM自动化操作是一个可选的方案。</li>
<li>DXF: 它被AutoCAD作为与其它软件之间进行CAD数据交换的文件格式，有不少开源库支持。</li>
</ul>
</blockquote>
<p>根据需求，进行一番测试，以便选择合适的库进行开发，如果你正好也想做类似的工作，希望对你亦有用。测试包括两项内容：</p>
<blockquote>
<ul>
<li>给定点集，自动绘制封闭的polyline</li>
<li>对第一步产生的封闭区域，自动填充。</li>
</ul>
</blockquote>
<h1 id="Python-生成DXF"><a href="#Python-生成DXF" class="headerlink" title="Python 生成DXF"></a>Python 生成DXF</h1><p>有不少开源库支持DXF文件的读取和写入,一些用纯Python语言写的，比如：</p>
<blockquote>
<ul>
<li><a href="https://github.com/davedoesdev/dxf" target="_blank" rel="noopener">dxf</a> version 0.8.9</li>
<li><a href="https://github.com/mozman/ezdxf" target="_blank" rel="noopener">ezdxf</a></li>
<li><a href="https://github.com/mozman/dxfgrabber" target="_blank" rel="noopener">dxfgrabber</a></li>
</ul>
</blockquote>
<p>也有重量级的，如GDAL。纯Python语言实现的库，在功能上还相对单薄。</p>
<h2 id="ezdxf"><a href="#ezdxf" class="headerlink" title="ezdxf"></a>ezdxf</h2><p>ezdxf文档还算不错，提供LWPoline 和 Hatch 函数，这正是我想要的。</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">import</span> ezdxf</span><br><span class="line"></span><br><span class="line"><span class="comment"># 简单起见，2个点集各包括4个点,形成两个长方形，小长方形在大长方形内部，类似“回”字。</span></span><br><span class="line">rect_points_outer = [(<span class="number">1.0</span>, <span class="number">1.0</span>), (<span class="number">8.0</span>, <span class="number">1.0</span>), (<span class="number">8.0</span>, <span class="number">8.0</span>), (<span class="number">1.0</span>, <span class="number">8.0</span>)]</span><br><span class="line">rect_points_inner = [(<span class="number">2.0</span>, <span class="number">2.0</span>), (<span class="number">7.0</span>, <span class="number">2.0</span>), (<span class="number">7.0</span>, <span class="number">7.0</span>), (<span class="number">2.0</span>, <span class="number">7.0</span>)]</span><br><span class="line"></span><br><span class="line"><span class="comment"># 函数不支持自动闭环，为了形成封闭区域，把第一个点增加到点集的尾部</span></span><br><span class="line">rect_points_outer.append(rect_points_outer[<span class="number">0</span>])</span><br><span class="line">rect_points_inner.append(rect_points_inner[<span class="number">0</span>])</span><br><span class="line"></span><br><span class="line">dwg = ezdxf.new(<span class="string">'R2010'</span>)</span><br><span class="line">modespace = dwg.modelspace()</span><br><span class="line">modespace.add_lwpolyline(rect_points_outer)</span><br><span class="line">modespace.add_lwpolyline(rect_points_inner)</span><br><span class="line">dwg.saveas(<span class="string">"rectangle.dxf"</span>)</span><br></pre></td></tr></table></figure>
<p>打开rectangle.dxf文件查看，效果不错，速度也很快。测试通过，除了polyline , 还支持Point, Circle, Arc, Ellipse, MTEXT等很多绘图实体, 自动绘图应该挺不错。下面测一下填充。</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">import</span> ezdxf</span><br><span class="line"></span><br><span class="line"><span class="comment"># 简单起见，2个点集各包括4个点,形成两个长方形，小长方形在大长方形内部，类似“回”字。</span></span><br><span class="line">rect_points_outer = [(<span class="number">1.0</span>, <span class="number">1.0</span>), (<span class="number">8.0</span>, <span class="number">1.0</span>), (<span class="number">8.0</span>, <span class="number">8.0</span>), (<span class="number">1.0</span>, <span class="number">8.0</span>)]</span><br><span class="line">rect_points_inner = [(<span class="number">2.0</span>, <span class="number">2.0</span>), (<span class="number">7.0</span>, <span class="number">2.0</span>), (<span class="number">7.0</span>, <span class="number">7.0</span>), (<span class="number">2.0</span>, <span class="number">7.0</span>)]</span><br><span class="line"></span><br><span class="line">dwg = ezdxf.new(<span class="string">'R2010'</span>)</span><br><span class="line">modespace = dwg.modelspace()</span><br><span class="line"></span><br><span class="line">hatch = msp.add_hatch(color=<span class="number">7</span>)</span><br><span class="line"><span class="keyword">with</span> hatch.edit_boundary() <span class="keyword">as</span> boundary:</span><br><span class="line">    boundary.add_polyline_path(rect_points_outer, is_closed=<span class="number">1</span>)</span><br><span class="line">    boundary.add_polyline_path(rect_points_inner, is_closed=<span class="number">1</span>)</span><br><span class="line"></span><br><span class="line"><span class="comment"># hatch 只能填充单个polyline封闭区域，而且很贴心的提供了自动闭合polyline。</span></span><br><span class="line"></span><br><span class="line">dwg.saveas(<span class="string">"rectangle.dxf"</span>)</span><br></pre></td></tr></table></figure>
<p>很遗憾，hatch函数目前还不支持多个polyline封闭区域的嵌套填空，也就是不能填充有空心的区域，不能满足需求。官方的文档提示 <a href="https://ezdxf.readthedocs.io/en/latest/tutorials/hatch.html#tut-hatch" target="_blank" rel="noopener">Create hatches with multiple boundary paths (islands) TODO</a>。</p>
<h2 id="dxfgrabber"><a href="#dxfgrabber" class="headerlink" title="dxfgrabber"></a>dxfgrabber</h2><p>dxfgrabber库支持的函数很多，绘图能力应该不错，但没有找到和填充有关的内容。</p>
<h2 id="其他"><a href="#其他" class="headerlink" title="其他"></a>其他</h2><p>其他的库，比如dxfwrite也大同小异，没有找到和填充有关的内容。</p>
<p>总结说来，几个纯Python库绘图能力还可以，但都不具备填充对个封闭Polyline区域的能力。ezdxf库已经开始支持Hatch函数，并且计划增加空心区域填充的功能，值得期待。</p>
<p>最后，只能把目光转移到其他开源库，纯Python库目前看能力还有限。这里介绍使用GDAL，这是一个核武器，处理空间地理信息的库，也支持矢量化操作，并且有Python绑定。最后完美的解决了这个问题。看看代码：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">from</span> osgeo <span class="keyword">import</span> ogr</span><br><span class="line"></span><br><span class="line"><span class="comment"># 简单起见，2个点集各包括4个点,形成两个长方形，小长方形在大长方形内部，类似“回”字。</span></span><br><span class="line">rect_points_outer = [(<span class="number">1.0</span>, <span class="number">1.0</span>), (<span class="number">8.0</span>, <span class="number">1.0</span>), (<span class="number">8.0</span>, <span class="number">8.0</span>), (<span class="number">1.0</span>, <span class="number">8.0</span>)]</span><br><span class="line">rect_points_inner = [(<span class="number">2.0</span>, <span class="number">2.0</span>), (<span class="number">7.0</span>, <span class="number">2.0</span>), (<span class="number">7.0</span>, <span class="number">7.0</span>), (<span class="number">2.0</span>, <span class="number">7.0</span>)]</span><br><span class="line">rect_points_outer.append(rect_points_outer[<span class="number">0</span>])</span><br><span class="line">rect_points_inner.append(rect_points_inner[<span class="number">0</span>])</span><br><span class="line"></span><br><span class="line">polys = [rect_points_outer, rect_points_inner]</span><br><span class="line">ogr.RegisterAll()</span><br><span class="line">driver = ogr.GetDriverByName(<span class="string">'DXF'</span>)</span><br><span class="line">datasource = driver.CreateDataSource(<span class="string">"rectangle.dxf"</span>)</span><br><span class="line">layer = datasource.CreateLayer(<span class="string">"Test"</span>, <span class="keyword">None</span>, ogr.wkbPolygon)</span><br><span class="line">ploygonFeature = ogr.Feature(layer.GetLayerDefn())</span><br><span class="line"><span class="comment"># 绘制轮廓</span></span><br><span class="line"><span class="keyword">for</span> poly <span class="keyword">in</span> polys:</span><br><span class="line">    contourLine = ogr.Geometry(ogr.wkbLineString)</span><br><span class="line">    <span class="keyword">for</span> point <span class="keyword">in</span> poly:</span><br><span class="line">        contourLine.AddPoint(float(point[<span class="number">0</span>]), float(point[<span class="number">1</span>]))</span><br><span class="line">    ploygonFeature.SetGeometry(contourLine)</span><br><span class="line">    layer.CreateFeature(ploygonFeature)</span><br><span class="line"></span><br><span class="line"><span class="comment"># 绘制填充</span></span><br><span class="line"><span class="comment"># outRing 为外部轮廓，innerRing 为内部轮廓。</span></span><br><span class="line"><span class="comment"># 内部有空洞的区域，必须先定义外部轮廓，然后再定义内部轮廓，内部轮廓可以有多个</span></span><br><span class="line"><span class="comment"># 多次调用AddGeometry函数即可。wkbPolygon 将 多一个 wkbLinearRing组合再一起</span></span><br><span class="line"><span class="comment"># 形成有内部空洞的封闭区域。</span></span><br><span class="line"><span class="comment"># ogr 中，polygon本来就是带填充的，画线需要用wkbLineString。</span></span><br><span class="line">outRing = ogr.Geometry(ogr.wkbLinearRing)</span><br><span class="line"><span class="keyword">for</span> point <span class="keyword">in</span> rect_points_outer:</span><br><span class="line">    outRing.AddPoint(point[<span class="number">0</span>], point[<span class="number">1</span>])</span><br><span class="line">outRing.CloseRings()</span><br><span class="line"></span><br><span class="line">innerRing = ogr.Geometry(ogr.wkbLinearRing)</span><br><span class="line"><span class="keyword">for</span> point <span class="keyword">in</span> rect_points_inner:</span><br><span class="line">    innerRing.AddPoint(point[<span class="number">0</span>], point[<span class="number">1</span>])</span><br><span class="line">innerRing.CloseRings()</span><br><span class="line"></span><br><span class="line">poly = ogr.Geometry(ogr.wkbPolygon)</span><br><span class="line">poly.AddGeometry(outRing)</span><br><span class="line">poly.AddGeometry(innerRing)</span><br><span class="line">ploygonFeature.SetGeometry(poly)</span><br><span class="line">layer.CreateFeature(ploygonFeature)</span><br></pre></td></tr></table></figure>
<p>完美！</p>
<h1 id="Pyhon-生成DWG"><a href="#Pyhon-生成DWG" class="headerlink" title="Pyhon 生成DWG"></a>Pyhon 生成DWG</h1><p>没有纯Python库支持，也没有开源的第三方库，好在AutoCAD支持COM。 用VB，c# 实现应该比较容易，但Python缺有点艰难。pyWin 和 comtypes 是两个可用的Pyton库，实现COM操作。但这两个库都久未更新，这条路也不是那么好走。 comtypes 看上去更新一点，用的也比较多，重点测试这个库。测试内容有两个，绘制封闭的Polyline，并对它进行填充。</p>
<p>直接用comtypes相对繁琐一点，有个俄罗斯人做了一个简单的封装，对表格读写做了加强，这个库叫pyautocad。先看看测试项目1，轮廓的绘制。代码很直接，结果很满意。</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">from</span> pyautocad <span class="keyword">import</span> Autocad</span><br><span class="line"><span class="keyword">import</span> numpy <span class="keyword">as</span> np</span><br><span class="line"></span><br><span class="line"><span class="comment"># 简单起见，2个点集各包括4个点,形成两个长方形，小长方形在大长方形内部，类似“回”字。</span></span><br><span class="line">rect_points_outer = [(<span class="number">1.0</span>, <span class="number">1.0</span>), (<span class="number">8.0</span>, <span class="number">1.0</span>), (<span class="number">8.0</span>, <span class="number">8.0</span>), (<span class="number">1.0</span>, <span class="number">8.0</span>)]</span><br><span class="line">rect_points_inner = [(<span class="number">2.0</span>, <span class="number">2.0</span>), (<span class="number">7.0</span>, <span class="number">2.0</span>), (<span class="number">7.0</span>, <span class="number">7.0</span>), (<span class="number">2.0</span>, <span class="number">7.0</span>)]</span><br><span class="line"></span><br><span class="line">acad = Autocad(create_if_not_exists=<span class="keyword">True</span>)</span><br><span class="line">modelspace = acad.model</span><br><span class="line">polys = []</span><br><span class="line"></span><br><span class="line"><span class="comment"># AddPolyLine 方法接收的参数和AddLine不同.Addline(pointa, pointb) 接收2个点作为输入。</span></span><br><span class="line"><span class="comment"># pointa=(xa, ya, za),pointb=(xb, yb, zb)</span></span><br><span class="line"><span class="comment"># AddPolyLine 接收坐标列表，且是一维的。AddPolyLine([xa, ya, za, xb, yb, zb])</span></span><br><span class="line">polyarray = np.array(rect_points_outer)</span><br><span class="line">z = np.zeros(<span class="number">3</span>)</span><br><span class="line">polyarray = np.column_stack(polyarray, z)</span><br><span class="line">polyarray = polyarray.reshape(<span class="number">1</span>, polyarray.shape[<span class="number">0</span>]*polyarray.shape[<span class="number">1</span>])[<span class="number">0</span>]</span><br><span class="line"></span><br><span class="line">poly = modelspace.AddPolyLine(polyarray)</span><br><span class="line">poly.color = <span class="number">1</span></span><br><span class="line">poly.closed = <span class="keyword">True</span></span><br><span class="line">acad.doc.SaveAs(<span class="string">"rectangle.dwg"</span>)</span><br></pre></td></tr></table></figure>
<p>完美，自动调用本机的Autocad，绘制轮廓后保存为dwg格式文件。</p>
<p>再看看测试项目2，绘制填充。查了一下Autocad 的ActiveX reference, 照葫芦画瓢，写个测试。</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">from</span> pyautocad <span class="keyword">import</span> Autocad</span><br><span class="line"><span class="keyword">import</span> numpy <span class="keyword">as</span> np</span><br><span class="line"></span><br><span class="line"><span class="comment"># 简单起见，2个点集各包括4个点,形成两个长方形，小长方形在大长方形内部，类似“回”字。</span></span><br><span class="line">rect_points_outer = [(<span class="number">1.0</span>, <span class="number">1.0</span>), (<span class="number">8.0</span>, <span class="number">1.0</span>), (<span class="number">8.0</span>, <span class="number">8.0</span>), (<span class="number">1.0</span>, <span class="number">8.0</span>)]</span><br><span class="line">rect_points_inner = [(<span class="number">2.0</span>, <span class="number">2.0</span>), (<span class="number">7.0</span>, <span class="number">2.0</span>), (<span class="number">7.0</span>, <span class="number">7.0</span>), (<span class="number">2.0</span>, <span class="number">7.0</span>)]</span><br><span class="line"></span><br><span class="line">acad = Autocad(create_if_not_exists=<span class="keyword">True</span>)</span><br><span class="line">modelspace = acad.model</span><br><span class="line"></span><br><span class="line"><span class="comment"># AddPolyLine 方法接收的参数和AddLine不同.Addline(pointa, pointb) 接收2个点作为输入。</span></span><br><span class="line"><span class="comment"># pointa=(xa, ya, za),pointb=(xb, yb, zb)</span></span><br><span class="line"><span class="comment"># AddPolyLine 接收坐标列表，且是一维的。AddPolyLine([xa, ya, za, xb, yb, zb])</span></span><br><span class="line">polyarray = np.array(rect_points_outer)</span><br><span class="line">z = np.zeros(<span class="number">3</span>)</span><br><span class="line">polyarray = np.column_stack(polyarray, z)</span><br><span class="line">polyarray = polyarray.reshape(<span class="number">1</span>, polyarray.shape[<span class="number">0</span>]*polyarray.shape[<span class="number">1</span>])[<span class="number">0</span>]</span><br><span class="line">poly = modelspace.AddPolyLine(polyarray)</span><br><span class="line">poly.color = <span class="number">1</span></span><br><span class="line">poly.closed = <span class="keyword">True</span></span><br><span class="line"></span><br><span class="line"><span class="comment"># AddHatch函数添加一个hatch对象.hatch对象有2个关键的函数，AppendOuterLoop和AppendInnerLoop。</span></span><br><span class="line"><span class="comment"># 内部有空洞的轮廓总是要先执行AppendOuterLoop函数，然后再执行AppendOuterLoop。</span></span><br><span class="line">hatch = modelspace.AddHatch(<span class="number">0</span>, <span class="string">'SOLID'</span>, <span class="keyword">True</span>)</span><br><span class="line">hatch.color = <span class="number">1</span></span><br><span class="line">hatch.AppendOuterLoop([poly])</span><br></pre></td></tr></table></figure>
<p>上面的测试代码没有写AppendOuterLoop函数，因为AppendOuterLoop函数就报错了。AppendOuterLoop和AppendInnerLoop函数接收的参数是AcadEntity的列表，在COM中，也就是VT_DISPATCH类型的列表。目前commtypes库只支持数字和日期的传递给函数。翻了一下，这个问题在很多年前就已经提出，但目前看，一直未解决。comtypes的<a href="https://github.com/enthought/comtypes/blob/master/comtypes/automation.py" target="_blank" rel="noopener">automation.py</a>依然写的 not yet implemented。估计作者已经不打算再更新了。</p>
<blockquote>
<ol>
<li><a href="https://sourceforge.net/p/comtypes/mailman/message/21280215/" target="_blank" rel="noopener">sourceforge 讨论1</a></li>
<li><a href="https://sourceforge.net/p/comtypes/mailman/message/20141047/" target="_blank" rel="noopener">sourceforge 讨论2</a></li>
</ol>
</blockquote>

      
    </div>
    
    
    

    

    

    

    <footer class="post-footer">
      

      
      
      

      

      
      
    </footer>
  </div>
  
  
  
  </article>



    <div class="post-spread">
      
    </div>
  </div>


          </div>
          


          

  



        </div>
        
          
  
  <div class="sidebar-toggle">
    <div class="sidebar-toggle-line-wrap">
      <span class="sidebar-toggle-line sidebar-toggle-line-first"></span>
      <span class="sidebar-toggle-line sidebar-toggle-line-middle"></span>
      <span class="sidebar-toggle-line sidebar-toggle-line-last"></span>
    </div>
  </div>

  <aside id="sidebar" class="sidebar">
    
    <div class="sidebar-inner">

      

      
        <ul class="sidebar-nav motion-element">
          <li class="sidebar-nav-toc sidebar-nav-active" data-target="post-toc-wrap">
            文章目录
          </li>
          <li class="sidebar-nav-overview" data-target="site-overview-wrap">
            站点概览
          </li>
        </ul>
      

      <section class="site-overview-wrap sidebar-panel">
        <div class="site-overview">
          <div class="site-author motion-element" itemprop="author" itemscope="" itemtype="http://schema.org/Person">
            
              <p class="site-author-name" itemprop="name">njhpq@hotmail.com</p>
              <p class="site-description motion-element" itemprop="description"></p>
          </div>

          <nav class="site-state motion-element">

            
              <div class="site-state-item site-state-posts">
              
                <a href="/archives/">
              
                  <span class="site-state-item-count">1</span>
                  <span class="site-state-item-name">日志</span>
                </a>
              </div>
            

            

            

          </nav>

          

          
            <div class="links-of-author motion-element">
                
                  <span class="links-of-author-item">
                    <a href="http://weibo.com/u/3877457378/" target="_blank" title="微博">
                      
                        <i class="fa fa-fw fa-globe"></i>微博</a>
                  </span>
                
            </div>
          

          
          

          
          

          

        </div>
      </section>

      
      <!--noindex-->
        <section class="post-toc-wrap motion-element sidebar-panel sidebar-panel-active">
          <div class="post-toc">

            
              
            

            
              <div class="post-toc-content"><ol class="nav"><li class="nav-item nav-level-1"><a class="nav-link" href="#Python-生成DXF"><span class="nav-number">1.</span> <span class="nav-text">Python 生成DXF</span></a><ol class="nav-child"><li class="nav-item nav-level-2"><a class="nav-link" href="#ezdxf"><span class="nav-number">1.1.</span> <span class="nav-text">ezdxf</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#dxfgrabber"><span class="nav-number">1.2.</span> <span class="nav-text">dxfgrabber</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#其他"><span class="nav-number">1.3.</span> <span class="nav-text">其他</span></a></li></ol></li><li class="nav-item nav-level-1"><a class="nav-link" href="#Pyhon-生成DWG"><span class="nav-number">2.</span> <span class="nav-text">Pyhon 生成DWG</span></a></li></ol></div>
            

          </div>
        </section>
      <!--/noindex-->
      

      

    </div>
  </aside>


        
      </div>
    </main>

    <footer id="footer" class="footer">
      <div class="footer-inner">
        <div class="copyright">&copy; <span itemprop="copyrightYear">2018</span>
  <span class="with-love">
    <i class="fa fa-user"></i>
  </span>
  <span class="author" itemprop="copyrightHolder">njhpq@hotmail.com</span>

  
</div>


  <div class="powered-by">由 <a class="theme-link" target="_blank" href="https://hexo.io">Hexo</a> 强力驱动</div>



  <span class="post-meta-divider">|</span>



  <div class="theme-info">主题 &mdash; <a class="theme-link" target="_blank" href="https://github.com/iissnan/hexo-theme-next">NexT.Muse</a> v5.1.4</div>




        







        
      </div>
    </footer>

    
      <div class="back-to-top">
        <i class="fa fa-arrow-up"></i>
        
      </div>
    

    

  </div>

  

<script type="text/javascript">
  if (Object.prototype.toString.call(window.Promise) !== '[object Function]') {
    window.Promise = null;
  }
</script>









  












  
  
    <script type="text/javascript" src="/lib/jquery/index.js?v=2.1.3"></script>
  

  
  
    <script type="text/javascript" src="/lib/fastclick/lib/fastclick.min.js?v=1.0.6"></script>
  

  
  
    <script type="text/javascript" src="/lib/jquery_lazyload/jquery.lazyload.js?v=1.9.7"></script>
  

  
  
    <script type="text/javascript" src="/lib/velocity/velocity.min.js?v=1.2.1"></script>
  

  
  
    <script type="text/javascript" src="/lib/velocity/velocity.ui.min.js?v=1.2.1"></script>
  

  
  
    <script type="text/javascript" src="/lib/fancybox/source/jquery.fancybox.pack.js?v=2.1.5"></script>
  


  


  <script type="text/javascript" src="/js/src/utils.js?v=5.1.4"></script>

  <script type="text/javascript" src="/js/src/motion.js?v=5.1.4"></script>



  
  

  
  <script type="text/javascript" src="/js/src/scrollspy.js?v=5.1.4"></script>
<script type="text/javascript" src="/js/src/post-details.js?v=5.1.4"></script>



  


  <script type="text/javascript" src="/js/src/bootstrap.js?v=5.1.4"></script>



  


  




	





  





  












  





  

  

  

  
  

  
  
    <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        tex2jax: {
          inlineMath: [ ['$','$'], ["\\(","\\)"]  ],
          processEscapes: true,
          skipTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code']
        }
      });
    </script>

    <script type="text/x-mathjax-config">
      MathJax.Hub.Queue(function() {
        var all = MathJax.Hub.getAllJax(), i;
        for (i=0; i < all.length; i += 1) {
          all[i].SourceElement().parentNode.className += ' has-jax';
        }
      });
    </script>
    <script type="text/javascript" src="//cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML"></script>
  


  

  

</body>
</html>
